### PR TITLE
Fix: #6 Embedded serial library has no license

### PR DESCRIPTION
**Pull request by rhl-bthr**
**Fixed in this PR:** #6 

Source of License: [here](https://github.com/pyserial/pyserial/blob/master/LICENSE.txt)

@quozl  Kindly review

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Will you be changing `activity.info`?  No license metadata yet.

**Comment by rhl-bthr** [comment]
Thank you.
**Changes made**: Added license metada in activity.info

**Comment by quozl** [comment]
Oh, sorry, I remember now that setting the metadata for license is way more complicated; a quick search of copyright and license in the repository shows GPLv2+ as well.

So `license = GPLv2;BSD 3`?  Or more?

https://wiki.sugarlabs.org/go/Development_Team/Almanac/Activity_Bundles#.info_file_format updated to show how we recently found activities.sugarlabs.org to be picky about the delimiter.

**Comment by rhl-bthr** [comment]
Update: added GPLv2.
Also added GPLv3, coming from source in `tabs/` and `monitor.py`

**Doubt**: if GPLv3 is being used, should I discard GPLv2 as the GPLv2 license reads:
`GPL version 2 or higher`

Didn't find any other license

**Pull request merged**
